### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by HHC26** [Madou-Shinni/gin-quickstart#2]
你好！后面还继续更新吗？如果有交流群请放出来下

**Comment by Madou-Shinni** [comment]
非常感谢您咨询，后续会继续更新，一般集中在引入一些工具和方案上。但是这并不是一个成熟的方案，我们推荐您在生产环境中使用**gin-vue-admin开发：https://github.com/flipped-aurora/gin-vue-admin**

**Comment by Madou-Shinni** [comment]
> 你好！后面还继续更新吗？如果有交流群请放出来下
非常感谢您咨询，后续会继续更新，一般集中在引入一些工具和方案上。但是这并不是一个成熟的方案，我们推荐您在生产环境中使用gin-vue-admin开发：https://github.com/flipped-aurora/gin-vue-admin

**Comment by Madou-Shinni** [comment]
> 你好！后面还继续更新吗？如果有交流群请放出来下

非常感谢您咨询，后续会继续更新，一般集中在引入一些工具和方案上。但是这并不是一个成熟的方案，我们推荐您在生产环境中使用gin-vue-admin开发：https://github.com/flipped-aurora/gin-vue-admin
