### ISSUE TITLE
生成的代码好像有问题

### ISSUE THREAD

**Issue by hzb888** [Madou-Shinni/gin-quickstart#4]
你好，我用的你脚手架 用你的生成代码的工具 生成了一个接口 没有自动注册 而且路由的参数类型 还不一样 
dome中是 gin.Engine
生成的是  gin.RouterGroup

**Comment by Madou-Shinni** [comment]
> 你好，我用的你脚手架 用你的生成代码的工具 生成了一个接口 没有自动注册 而且路由的参数类型 还不一样 dome中是 gin.Engine 生成的是 gin.RouterGroup

参考了您的问题，已经做出解决

与初始化的路由进行了更改，希望能在更大范围上对聚合的路由组进行管理，如下示例

```go
// 设置路由组
public := r.Group("")
//private := r.Group("private")

// 注册路由
routers.DemoRouterRegister(public)
routers.FileRouterRegister(r)
```

同时更新了代码生成的方案，现在支持自动注册路由和数据库结构自动迁移，请您使用gctl v1.2.0
